---
- hosts: all
  gather_facts: yes
  become: no

  vars:
    docker_mycroft_workdir: ~/docker-mycroft
    docker_mycroft_repository: https://github.com/smartgic/docker-mycroft.git
    docker_mycroft_branch: master
    docker_mycroft_namespace: smartgic
    docker_mycroft_tag: latest
    docker_mycroft_stable_release: 21.2.1
    docker_mycroft_version: master
    docker_mycroft_username:
    docker_mycroft_password:

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_mycroft_username }}"
        password: "{{ docker_mycroft_password }}"

    - name: Retrieve Dockerfiles from Git
      ansible.builtin.git:
        repo: "{{ docker_mycroft_repository }}"
        dest: "{{ docker_mycroft_workdir }}"
        version: "{{ docker_mycroft_branch }}"

    - name: Build Docker dev images
      ansible.builtin.shell:
        cmd: >-
          docker buildx build
          -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:{{ docker_mycroft_tag }}
          -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:latest
          --build-arg TAG={{ docker_mycroft_tag }}
          --build-arg BRANCH={{ docker_mycroft_version }}
          --platform linux/amd64,linux/arm64,linux/arm/v7
          --no-cache
          --push {{ item }}/
        executable: /bin/bash
        chdir: "{{ docker_mycroft_workdir }}"
      loop:
        - base
        - audio
        - bus
        - cli
        - enclosure
        - skills
        - voice
      when: docker_mycroft_version == "dev"

    - name: Build Docker stable images
      ansible.builtin.shell:
        cmd: >-
          docker buildx build
          -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:{{ docker_mycroft_tag }}
          -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:stable
          -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:{{ docker_mycroft_stable_release }}
          --build-arg TAG={{ docker_mycroft_tag }}
          --build-arg BRANCH={{ docker_mycroft_version }}
          --platform linux/amd64,linux/arm64,linux/arm/v7
          --no-cache
          --push {{ item }}/
        executable: /bin/bash
        chdir: "{{ docker_mycroft_workdir }}"
      loop:
        - base
        - audio
        - bus
        - cli
        - enclosure
        - skills
        - voice
      when: docker_mycroft_version == "master"

    - name: Logout from DockerHub
      community.docker.docker_login:
        state: absent
