---
- name: Clean Open Voice OS Docker images build
  hosts: all
  gather_facts: no

  vars:
    docker_ovos_workdir: ~/docker-ovos
    docker_ovos_cosign_key_path: ~/cosign.key
    docker_ovos_cosign: false

  tasks:
    - name: Logout from Docker Hub
      community.docker.docker_login:
        state: absent

    - name: Remove Git project
      ansible.builtin.file:
        path: "{{ docker_ovos_workdir }}"
        state: absent

    - name: Remove Cosign private key
      ansible.builtin.file:
        path: "{{ docker_ovos_cosign_key_path }}"
        state: absent
      when: docker_ovos_cosign | bool
