---
- name: Prepare Open Voice OS Docker images build
  hosts: all
  gather_facts: no

  vars:
    docker_ovos_workdir: ~/docker-ovos
    docker_ovos_cosign_key_path: ~/cosign.key
    docker_ovos_repository: https://github.com/OpenVoiceOS/ovos-docker.git
    docker_ovos_branch: feat/alpine
    docker_ovos_cosign: false

  tasks:
    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ docker_ovos_username }}"
        password: "{{ docker_ovos_password }}"

    - name: Retrieve Dockerfiles from Git
      ansible.builtin.git:
        repo: "{{ docker_ovos_repository }}"
        dest: "{{ docker_ovos_workdir }}"
        version: "{{ docker_ovos_branch }}"

    - name: Create Cosign private key
      ansible.builtin.copy:
        content: "{{ cosign_private_key }}"
        dest: "{{ docker_ovos_cosign_key_path }}"
        mode: 0400
      when: docker_ovos_cosign | bool
