---
- name: Build Open Voice OS Docker images
  hosts: all
  gather_facts: no
  become: no

  vars:
    docker_ovos_workdir: ~/docker-ovos
    docker_ovos_namespace: smartgic
    docker_ovos_stable_release: 0.0.8
    docker_ovos_version: master
    docker_ovos_arch: linux/amd64
    docker_ovos_image: base

  tasks:
    - name: ALPHA - Build ovos-{{ docker_ovos_image + "-" + docker_ovos_arch }}
      ansible.builtin.shell:
        cmd: >-
          docker buildx build
          --no-cache
          -t {{ docker_ovos_namespace }}/ovos-{{ docker_ovos_image }}:alpha
          -t {{ docker_ovos_namespace }}/ovos-{{ docker_ovos_image }}:{{ docker_ovos_stable_release }}a
          --build-arg ALPHA=true
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg VERSION={{ docker_ovos_stable_release }}a
          --platform {{ docker_ovos_arch }}
          --push {{ docker_ovos_image }}/
        executable: /bin/bash
        chdir: "{{ docker_ovos_workdir }}"
      register: dev_build_output
      changed_when: dev_build_output.rc == 0
      when: docker_ovos_version == "alpha"

    - name: STABLE - Build ovos-{{ docker_ovos_image + "-" + docker_ovos_arch }}
      ansible.builtin.shell:
        cmd: >-
          docker buildx build
          --no-cache
          -t {{ docker_ovos_namespace }}/ovos-{{ docker_ovos_image }}:stable
          -t {{ docker_ovos_namespace }}/ovos-{{ docker_ovos_image }}:{{ docker_ovos_stable_release }}
          --build-arg ALPHA=false
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg VERSION={{ docker_ovos_stable_release }}
          --platform {{ docker_ovos_arch }}
          --push {{ docker_ovos_image }}/
        executable: /bin/bash
        chdir: "{{ docker_ovos_workdir }}"
      register: stable_build_output
      changed_when: stable_build_output.rc == 0
      when: docker_ovos_version == "master"
